Update assignment3.yml
Added new action to the workflow

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -13,19 +13,50 @@ jobs:
         
       - name: Add submitters names
         run: echo "Yonathan Gleit, Nir Sharon" >> log.txt
-        
-      - name: Retrieve Log File
+      
+      - name: Setup Docker
+        uses: docker/setup-buildx-action@v2
+      
+      - name: Build Docker image
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          dockerfile: Dockerfile
+          push: false
+          tags: cloud-computing-homework-3
+          
+      - name: Check If Image Was Successfully bulid
+        id: image-check
+        run: |
+          if [[ success() ]]; then 
+            echo "image successfully built" >> log.txt
+          else
+            echo "image not able to be built" >> log.txt
+            exit 1
+          fi
+          
+      - name: Run Docker Image
+        if: steps.image-check.outputs.success == 'true'
+        uses: docker/cli@v2
+        with:
+          command: run cloud-computing-homework-3
+          
+      - name: Check If Image Ran Successfully
+        id: Running-check
+        run: |
+          if [[ success() ]]; then 
+            echo "Container up and running" >> log.txt
+          else
+            echo "Container failed to run" >> log.txt
+            exit 1
+          fi
+      
+      - name: Retrieve When Failed Log File
+        if: ${{ failure() }}
         uses: actions/upload-artifact@v3
         with:
-          name: log.txt
+          name: log
           path: log.txt
+          
+          
 
-#      - name: Build Docker image
-#        run: docker build -t yglrit/cloud-computing-homework:latest .
-
-#  test:
-#    needs: build
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout repository
-#        uses: actions/checkout@v2
